importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [ ]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/25k IMDb movie Dataset.csv')

In [ ]:
# printing the first 5 rows of the dataframe
movies_data.head()

movie title                  Run Time Rating User Rating  \
0        Top Gun: Maverick  $170,000,000 (estimated)    8.6        187K   
1  Jurassic World Dominion        2 hours 27 minutes      6         56K   
2                  Top Gun   $15,000,000 (estimated)    6.9        380K   
3                Lightyear               $71,101,257    5.2         32K   
4               Spiderhead              not-released    5.4         23K   

                                Generes  \
0                   ['Action', 'Drama']   
1     ['Action', 'Adventure', 'Sci-Fi']   
2                   ['Action', 'Drama']   
3  ['Animation', 'Action', 'Adventure']   
4          ['Action', 'Crime', 'Drama']   

                                            Overview  \
0  After more than thirty years of service as one...   
1  Four years after the destruction of Isla Nubla...   
2  As students at the United States Navy's elite ...   
3  While spending years attempting to return home...   
4  In the near future, convicts are offered the c...   

                                        Plot Kyeword         Director  \
0  ['fighter jet', 'sequel', 'u.s. navy', 'fighte...  Joseph Kosinski   
1  ['dinosaur', 'jurassic park', 'tyrannosaurus r...  Colin Trevorrow   
2  ['pilot', 'male camaraderie', 'u.s. navy', 'gr...       Tony Scott   
3  ['galaxy', 'spaceship', 'robot', 'rocket', 'sp...    Angus MacLane   
4  ['discover', 'medical', 'test', 'reality', 'fi...  Joseph Kosinski   

                                         Top 5 Casts            Writer   year  \
0  ['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...          Jim Cash  -2022   
1  ['Colin Trevorrow', 'Derek Connolly', 'Chris P...  Emily Carmichael  -2022   
2  ['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...          Jim Cash  -1986   
3  ['Jason Headley', 'Matthew Aldrich', 'Chris Ev...     Angus MacLane  -2022   
4  ['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...   George Saunders  -2022   

                 path  
0   /title/tt1745960/  
1   /title/tt8041270/  
2   /title/tt0092099/  
3  /title/tt10298810/  
4   /title/tt9783600/

In [ ]:
# number of rows and columns in the data frame
movies_data.shape

(24402, 12)

In [ ]:
# selecting the relevent features for recommendation
selected_features = ['Generes','Overview','Plot Kyeword','movie title','Rating']
print(selected_features)

['Generes', 'Overview', 'Plot Kyeword', 'movie title', 'Rating']


In [ ]:
# replacing the null values with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
# combining all the 5 selected features

combined_features = movies_data['Generes']+''+movies_data['Overview']+''+movies_data['Plot Kyeword']+''+movies_data['movie title']+''+movies_data['Rating']
print(combined_features)

0        ['Action', 'Drama']After more than thirty year...
1        ['Action', 'Adventure', 'Sci-Fi']Four years af...
2        ['Action', 'Drama']As students at the United S...
3        ['Animation', 'Action', 'Adventure']While spen...
4        ['Action', 'Crime', 'Drama']In the near future...
                               ...                        
24397    ['Comedy', 'Crime']Post-apocalyptic surrealist...
24398    ['Crime', 'Horror']A gang initiation goes wron...
24399    ['Crime', 'Romance', 'Western']In order to avo...
24400    ['Comedy', 'Crime']An N.Y.C. film school stude...
24401    ['Comedy', 'Crime', 'Musical']In New York, a g...
Length: 24402, dtype: object


In [ ]:
# converting the text data to feature vectors
vectorizer = TfidfVectorizer()


In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 32010)	0.19045584548521163
  (0, 22039)	0.08494335792498199
  (0, 32834)	0.09021653042542085
  (0, 4168)	0.2931646667318323
  (0, 34706)	0.1279228087946809
  (0, 1878)	0.2558456175893618
  (0, 45230)	0.08631030357824819
  (0, 26739)	0.2616870195944271
  (0, 18676)	0.3288172560176357
  (0, 21846)	0.12620623745782875
  (0, 56154)	0.11170576237229989
  (0, 50775)	0.05470036142518194
  (0, 41033)	0.1703548927421682
  (0, 25037)	0.02967752837031948
  (0, 1539)	0.1777735563244917
  (0, 15072)	0.1576726035814483
  (0, 2626)	0.02870129288863012
  (0, 38431)	0.32083034081570605
  (0, 50660)	0.10993943923044955
  (0, 11927)	0.1576726035814483
  (0, 17083)	0.15129974895949697
  (0, 40356)	0.16293622915984465
  (0, 5585)	0.15240897800305195
  (0, 22908)	0.05145793178067541
  (0, 55430)	0.07589136286861536
  :	:
  (24401, 20299)	0.09788051748123339
  (24401, 56535)	0.17237562520423094
  (24401, 8053)	0.06742399992705796
  (24401, 33166)	0.09994492426272719
  (24401, 23406)	0.11674265262860405

Cosine similarity

In [ ]:
# getting the similarity scores using cosine similarity
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.02768034 0.41165072 ... 0.00985087 0.0130778  0.00637833]
 [0.02768034 1.         0.0131341  ... 0.01277362 0.01798755 0.03094224]
 [0.41165072 0.0131341  1.         ... 0.00985063 0.02728152 0.01827459]
 ...
 [0.00985087 0.01277362 0.00985063 ... 1.         0.01174758 0.02394659]
 [0.0130778  0.01798755 0.02728152 ... 0.01174758 1.         0.01678608]
 [0.00637833 0.03094224 0.01827459 ... 0.02394659 0.01678608 1.        ]]


In [ ]:
print(similarity.shape)

(24402, 24402)


In [ ]:
# getting the movie information from the user
movie_name = input(' Describe your movie : ')

 Describe your movie : Top gun


In [ ]:
# creating a list all the movie names given in the dataset
list_of_all_titles = movies_data['movie title'].tolist()
print(list_of_all_titles)

['Top Gun: Maverick', 'Jurassic World Dominion', 'Top Gun', 'Lightyear', 'Spiderhead', 'Everything Everywhere All at Once', 'Interceptor', 'Interceptor', 'Black Adam', 'The Northman', 'Thor: Love and Thunder', 'Fantastic Beasts: The Secrets of Dumbledore', 'The Unbearable Weight of Massive Talent', 'Jurassic Park', 'Doctor Strange in the Multiverse of Madness', 'No Time to Die', 'The Batman', 'Bullet Train', 'Bullet Train', 'Jurassic World', 'Jurassic World: Fallen Kingdom', 'Vikram', 'Morbius', 'The Lost City', 'Spider-Man: No Way Home', 'Last Seen Alive', 'Sonic the Hedgehog 2', 'Uncharted', 'Prey', 'Prey', 'Prey', 'Ambulance', 'Ambulance', 'The Lost World: Jurassic Park', 'Dune', 'Dune', 'Jurassic Park III', 'Star Wars', 'The Gray Man', 'Avengers: Endgame', 'The Lady of Heaven', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'Eternals', 'Free Guy', 'The Matrix Resurrections', 'Mission: Impossible', 'Memory', 'Memory', 'Star Wars: Episode I - The Phantom Menace', 'The Adam

In [ ]:
# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Top Gun', 'Top Dog', 'Top Gunner']


In [ ]:
close_match = find_close_match[0]
print(close_match)

Top Gun


In [ ]:
# finding the index of the movie with title

#index_of_the_movie = movies_data[movies_data.title == close_match]['path'].values[0]
#print(index_of_the_movie)
filtered_data_exact = movies_data[movies_data['movie title'] == close_match]

# Get the index of the matching row(s)
matching_indices_exact = filtered_data_exact.index
matching_indices_exact[0]

2

In [ ]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[matching_indices_exact[0]]))
print(similarity_score)

[(0, 0.41165072435374117), (1, 0.013134096698652052), (2, 1.0), (3, 0.009030865155045635), (4, 0.027582253804969068), (5, 0.015794207843392857), (6, 0.019684097318452578), (7, 0.004443955424234897), (8, 0.016639918816761926), (9, 0.022434216023987975), (10, 0.0191018672789349), (11, 0.010113140231450643), (12, 0.018128659216113823), (13, 0.005703625038952594), (14, 0.015034156593317598), (15, 0.009448374277752353), (16, 0.010794043768908978), (17, 0.0055979637173345035), (18, 0.00603271664488981), (19, 0.0052065280755387725), (20, 0.011877159143001375), (21, 0.030149490814193453), (22, 0.008890251747984343), (23, 0.012159319577534385), (24, 0.011928870137431541), (25, 0.03745091118028913), (26, 0.01577711092890856), (27, 0.007123587170953209), (28, 0.024047947599267216), (29, 0.04291710709900962), (30, 0.010220447537988323), (31, 0.004533205585293306), (32, 0.031216872393366225), (33, 0.008429436194118624), (34, 0.00908630779148995), (35, 0.011434364495512434), (36, 0.00854785333550584

In [ ]:
print(similarity_score[0][1])

0.41165072435374117


In [ ]:
len(similarity_score)

24402

In [ ]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(2, 1.0), (0, 0.41165072435374117), (3866, 0.32871422764261465), (437, 0.3245892938830729), (2888, 0.29401422034752167), (16368, 0.29142624186614013), (953, 0.2911561305118322), (7367, 0.28223896477002314), (4486, 0.26715060591827283), (915, 0.26013683050395825), (6868, 0.2399748187964385), (1167, 0.23549494656528128), (2713, 0.22549313092227735), (1671, 0.22280146026781628), (20316, 0.22225193554076392), (20338, 0.21868220209459321), (1850, 0.20870927433250017), (2052, 0.2071133769358719), (2887, 0.20110775617619223), (1998, 0.19690314068986775), (16820, 0.1963303953383043), (20965, 0.19424367114096996), (2029, 0.1921603241258787), (12705, 0.19056274566718176), (4884, 0.19040659395519663), (7233, 0.19012934161531148), (2512, 0.18122704847677246), (2122, 0.17911070572505036), (2070, 0.1787138779379501), (4927, 0.1714725681540969), (10051, 0.16052261119912054), (8722, 0.16038582029714382), (3686, 0.1601605517644138), (8484, 0.1598398787027675), (49, 0.159798099440031), (1848, 0.1574380

In [ ]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['movie title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Top Gun
2 . Top Gun: Maverick
3 . Fighter Squadron
4 . Hot Shots!
5 . Wing Commander
6 . Captain Nova
7 . Devotion
8 . Stealth Fighter
9 . Flying Tigers
10 . Iron Eagle
11 . Black Thunder
12 . Behind Enemy Lines
13 . The Blue Max
14 . Sky Captain and the World of Tomorrow
15 . The Wings of Eagles
16 . Burning Blue
17 . Flight of the Intruder
18 . Come Out Fighting
19 . Jet Pilot
20 . Flyboys
21 . Lt. Robin Crusoe, U.S.N.
22 . The Great Waldo Pepper
23 . The High and the Mighty
24 . The Bridges at Toko-Ri
25 . The Hunters
26 . Death Warrior
27 . Always
28 . Flying Leathernecks
29 . Airport 1975


In [ ]:
movie_name = input(' Describe your movie : ')

list_of_all_titles = movies_data['movie title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

filtered_data_exact = movies_data[movies_data['movie title'] == close_match]

matching_indices_exact = filtered_data_exact.index

similarity_score = list(enumerate(similarity[matching_indices_exact[0]]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['movie title'].values[0]
  if (i<6):
    print(i, '.',title_from_index)
    i+=1

 Describe your movie : alien
Movies suggested for you : 

1 . Alien
2 . Star Crystal
3 . Passengers
4 . Pandorum
5 . Solis
